name: Build macOS Portable Binary

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
        type: string
      build_type:
        description: 'Build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
      create_dmg:
        description: 'Create DMG package'
        required: true
        default: true
        type: boolean
      code_sign:
        description: 'Code sign the application (requires secrets)'
        required: true
        default: false
        type: boolean

env:
  QT_VERSION: '6.5.0'
  CMAKE_BUILD_TYPE: ${{ inputs.build_type }}

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    
    - name: Get build info
      id: build_info
      run: |
        echo "git_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "git_branch=${{ inputs.branch }}" >> $GITHUB_OUTPUT
        echo "build_date=$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
        echo "app_name=DroidStar_${{ inputs.branch }}_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtmultimedia qtserialport'
        cache: true
    
    - name: Set Qt environment variables
      run: |
        # The Qt installer puts Qt in a predictable location
        QT_ROOT_DIR="/Users/runner/work/DroidStar/Qt/${{ env.QT_VERSION }}/macos"
        echo "QT_ROOT_DIR=$QT_ROOT_DIR" >> $GITHUB_ENV
        echo "Qt6_DIR=$QT_ROOT_DIR" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$QT_ROOT_DIR" >> $GITHUB_ENV
        
        # Add Qt binaries to PATH
        echo "$QT_ROOT_DIR/bin" >> $GITHUB_PATH
        
        # Verify the Qt installation
        echo "=== Qt Installation Verification ==="
        echo "Qt root: $QT_ROOT_DIR"
        ls -la "$QT_ROOT_DIR" || echo "Qt root directory not found"
        ls -la "$QT_ROOT_DIR/bin" || echo "Qt bin directory not found"
        ls -la "$QT_ROOT_DIR/lib" | head -5 || echo "Qt lib directory not found"
    
    - name: Install dependencies via Homebrew
      run: |
        # Update Homebrew and install dependencies (avoid Qt to prevent conflicts)
        brew update
        brew install cmake rtmidi pkg-config
        
        # Verify installations
        echo "=== Installed versions ==="
        cmake --version
        pkg-config --modversion rtmidi
        echo "Qt version: ${{ env.QT_VERSION }}"
        echo "Qt location: $QT_ROOT_DIR"
        
        # Verify Qt installation from GitHub Actions
        echo "=== Qt verification ==="
        ls -la "$QT_ROOT_DIR/lib" | head -10
        echo "macdeployqt location:"
        which macdeployqt
        ls -la "$QT_ROOT_DIR/bin/macdeployqt"
    
    - name: Configure build environment
      run: |
        # Set up ARM64 build (modern Macs, matches Homebrew architecture)
        echo "CMAKE_OSX_ARCHITECTURES=arm64" >> $GITHUB_ENV
        echo "CMAKE_OSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
        
        # Verify Qt tools are available
        which qmake6 || which qmake
        which macdeployqt
    
    - name: Create build directory
      run: |
        mkdir -p build
        cd build
        echo "Build directory created in: $(pwd)"
    
    - name: Configure with CMake
      working-directory: build
      run: |
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
          -DCMAKE_OSX_ARCHITECTURES="${{ env.CMAKE_OSX_ARCHITECTURES }}" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.CMAKE_OSX_DEPLOYMENT_TARGET }} \
          -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
          -DENABLE_MIDI=ON \
          -DCMAKE_VERBOSE_MAKEFILE=ON
    
    - name: Build application
      working-directory: build
      run: |
        echo "=== Starting build ==="
        make -j$(sysctl -n hw.ncpu) VERBOSE=1
        
        echo "=== Build completed ==="
        ls -la DroidStar.app/Contents/MacOS/
        
        echo "=== Checking binary architecture ==="
        file DroidStar.app/Contents/MacOS/DroidStar
        lipo -info DroidStar.app/Contents/MacOS/DroidStar || echo "lipo info failed"
    
    - name: Verify dependencies before deployment
      working-directory: build
      run: |
        echo "=== Pre-deployment dependency check ==="
        otool -L DroidStar.app/Contents/MacOS/DroidStar | head -15
        
        echo "=== App bundle structure ==="
        find DroidStar.app -type f -name "*.dylib" | head -10 || echo "No dylibs found yet"
    
    - name: Create portable app bundle
      working-directory: build
      run: |
        echo "=== Creating portable app bundle ==="
        cp -r DroidStar.app "${{ steps.build_info.outputs.app_name }}.app"
        
        echo "=== Qt environment debug ==="
        echo "QT_ROOT_DIR: $QT_ROOT_DIR"
        echo "PATH: $PATH"
        echo "Using macdeployqt from: $QT_ROOT_DIR/bin/macdeployqt"
        ls -la "$QT_ROOT_DIR/bin/macdeployqt"
        
        # Use the specific macdeployqt from our Qt installation
        MACDEPLOYQT="$QT_ROOT_DIR/bin/macdeployqt"
        
        echo "=== Pre-deployment dependency check ==="
        echo "Before macdeployqt:"
        otool -L "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" | head -10
        
        echo "=== Deploying Qt frameworks and dependencies ==="
        echo "macdeployqt command: $MACDEPLOYQT"
        echo "Target app: ${{ steps.build_info.outputs.app_name }}.app"
        
        # Run macdeployqt and capture both stdout and stderr
        if [ "${{ inputs.code_sign }}" = "true" ] && [ -n "${{ secrets.DEVELOPER_ID_APPLICATION }}" ]; then
          echo "Code signing enabled"
          echo "Running: $MACDEPLOYQT ${{ steps.build_info.outputs.app_name }}.app -codesign=${{ secrets.DEVELOPER_ID_APPLICATION }} -verbose=2"
          "$MACDEPLOYQT" "${{ steps.build_info.outputs.app_name }}.app" \
            -codesign="${{ secrets.DEVELOPER_ID_APPLICATION }}" \
            -verbose=2 2>&1 | tee macdeployqt_output.log
          MACDEPLOYQT_EXIT_CODE=${PIPESTATUS[0]}
        else
          echo "Building without code signing"
          echo "Running: $MACDEPLOYQT ${{ steps.build_info.outputs.app_name }}.app -verbose=2"
          "$MACDEPLOYQT" "${{ steps.build_info.outputs.app_name }}.app" \
            -verbose=2 2>&1 | tee macdeployqt_output.log
          MACDEPLOYQT_EXIT_CODE=${PIPESTATUS[0]}
        fi
        
        echo "=== macdeployqt results ==="
        echo "Exit code: $MACDEPLOYQT_EXIT_CODE"
        echo "Output:"
        cat macdeployqt_output.log
        
        if [ $MACDEPLOYQT_EXIT_CODE -ne 0 ]; then
          echo "❌ macdeployqt failed with exit code $MACDEPLOYQT_EXIT_CODE"
          exit 1
        fi
        
        echo "=== Post-deployment dependency check ==="
        echo "After macdeployqt:"
        otool -L "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" | head -10
        
        echo "=== Check what frameworks were actually copied ==="
        if [ -d "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/" ]; then
          echo "Frameworks directory exists:"
          ls -la "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/"
        else
          echo "❌ No Frameworks directory created by macdeployqt!"
          
          echo "=== Manual framework bundling attempt ==="
          mkdir -p "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/"
          
          # Try to find and copy Qt frameworks manually
          echo "Available Qt frameworks:"
          ls -la "$QT_ROOT_DIR/lib/"*.framework/ | head -5
          
          echo "Attempting manual copy of essential frameworks..."
          for framework in QtCore QtGui QtQml QtQuick QtQuickControls2 QtMultimedia QtNetwork QtSerialPort QtOpenGL QtQmlModels; do
            if [ -d "$QT_ROOT_DIR/lib/${framework}.framework" ]; then
              echo "Copying ${framework}.framework..."
              cp -R "$QT_ROOT_DIR/lib/${framework}.framework" "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/"
            else
              echo "⚠️ ${framework}.framework not found"
            fi
          done
          
          echo "=== Frameworks after manual copy ==="
          ls -la "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/"
        fi
        
        echo "=== Fixing library paths with install_name_tool ==="
        MAIN_BINARY="${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar"
        
        # Fix Qt framework paths in the main binary
        echo "Fixing Qt framework paths in main binary..."
        install_name_tool -change "@rpath/QtCore.framework/Versions/A/QtCore" "@executable_path/../Frameworks/QtCore.framework/Versions/A/QtCore" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtGui.framework/Versions/A/QtGui" "@executable_path/../Frameworks/QtGui.framework/Versions/A/QtGui" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtQml.framework/Versions/A/QtQml" "@executable_path/../Frameworks/QtQml.framework/Versions/A/QtQml" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtQuick.framework/Versions/A/QtQuick" "@executable_path/../Frameworks/QtQuick.framework/Versions/A/QtQuick" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtQuickControls2.framework/Versions/A/QtQuickControls2" "@executable_path/../Frameworks/QtQuickControls2.framework/Versions/A/QtQuickControls2" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtQmlModels.framework/Versions/A/QtQmlModels" "@executable_path/../Frameworks/QtQmlModels.framework/Versions/A/QtQmlModels" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtMultimedia.framework/Versions/A/QtMultimedia" "@executable_path/../Frameworks/QtMultimedia.framework/Versions/A/QtMultimedia" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtNetwork.framework/Versions/A/QtNetwork" "@executable_path/../Frameworks/QtNetwork.framework/Versions/A/QtNetwork" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtSerialPort.framework/Versions/A/QtSerialPort" "@executable_path/../Frameworks/QtSerialPort.framework/Versions/A/QtSerialPort" "$MAIN_BINARY"
        install_name_tool -change "@rpath/QtOpenGL.framework/Versions/A/QtOpenGL" "@executable_path/../Frameworks/QtOpenGL.framework/Versions/A/QtOpenGL" "$MAIN_BINARY"
        
        echo "=== Verifying fixed paths ==="
        otool -L "$MAIN_BINARY" | head -15
    
    - name: Verify portable app
      working-directory: build
      run: |
        echo "=== Post-deployment verification ==="
        echo "App size: $(du -sh ${{ steps.build_info.outputs.app_name }}.app)"
        
        echo "=== Checking complete app bundle structure ==="
        find "${{ steps.build_info.outputs.app_name }}.app" -type f | head -20
        
        echo "=== Checking bundled frameworks ==="
        if [ -d "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/" ]; then
          ls -la "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/" | head -10
          echo "Framework count: $(ls "${{ steps.build_info.outputs.app_name }}.app/Contents/Frameworks/" | wc -l)"
        else
          echo "❌ No Frameworks directory found!"
        fi
        
        echo "=== Checking Qt plugins ==="
        if [ -d "${{ steps.build_info.outputs.app_name }}.app/Contents/PlugIns/" ]; then
          find "${{ steps.build_info.outputs.app_name }}.app/Contents/PlugIns/" -name "*.dylib" | head -10
        else
          echo "❌ No PlugIns directory found!"
        fi
        
        echo "=== Final dependency check ==="
        otool -L "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar"
        
        echo "=== Checking for broken links ==="
        BROKEN_DEPS=$(otool -L "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" | grep -v "@executable_path" | grep -v "@loader_path" | grep -v "/usr/lib" | grep -v "/System" | tail -n +2 | awk '{print $1}' | while read dep; do
          if [ ! -f "$dep" ]; then
            echo "BROKEN: $dep"
          fi
        done)
        
        if [ -n "$BROKEN_DEPS" ]; then
          echo "❌ Found broken dependencies:"
          echo "$BROKEN_DEPS"
        else
          echo "✅ No broken external dependencies found"
        fi
        
        echo "=== Verifying architecture of deployed app ==="
        file "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar"
        lipo -info "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" || echo "lipo failed"
        
        echo "=== Checking app bundle requirements ==="
        echo "Info.plist exists: $(test -f "${{ steps.build_info.outputs.app_name }}.app/Contents/Info.plist" && echo "YES" || echo "NO")"
        echo "Executable exists: $(test -f "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" && echo "YES" || echo "NO")"
        echo "Executable permissions: $(ls -la "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" | awk '{print $1}')"
        
        # Test if we can at least get version info without GUI
        echo "=== Testing executable linking (no GUI launch) ==="
        # Just verify the binary can be loaded without actually running it
        echo "Checking if binary can be loaded (using otool to verify it's not corrupted):"
        otool -h "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" > /dev/null && echo "✅ Binary appears valid" || echo "❌ Binary appears corrupted"
        
        # Skip actual execution to avoid GUI initialization and potential hanging
        
        echo "=== Bundle verification summary ==="
        if [ -f "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" ] && [ -x "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" ]; then
          echo "✅ Main executable exists and is executable"
        else
          echo "❌ Main executable missing or not executable"
          exit 1
        fi
    
    - name: Create DMG package
      if: ${{ inputs.create_dmg }}
      working-directory: build
      run: |
        echo "=== Creating DMG package ==="
        if [ "${{ inputs.code_sign }}" = "true" ] && [ -n "${{ secrets.DEVELOPER_ID_APPLICATION }}" ]; then
          macdeployqt "${{ steps.build_info.outputs.app_name }}.app" \
            -dmg \
            -codesign="${{ secrets.DEVELOPER_ID_APPLICATION }}"
        else
          macdeployqt "${{ steps.build_info.outputs.app_name }}.app" -dmg
        fi
        
        # Rename DMG to include build info
        if [ -f "${{ steps.build_info.outputs.app_name }}.dmg" ]; then
          mv "${{ steps.build_info.outputs.app_name }}.dmg" \
             "${{ steps.build_info.outputs.app_name }}_${{ steps.build_info.outputs.build_date }}.dmg"
          echo "DMG created: ${{ steps.build_info.outputs.app_name }}_${{ steps.build_info.outputs.build_date }}.dmg"
          echo "DMG size: $(du -sh ${{ steps.build_info.outputs.app_name }}_${{ steps.build_info.outputs.build_date }}.dmg)"
        fi
    
    - name: Create build summary
      working-directory: build
      run: |
        echo "=== Build Summary ===" > build_summary.txt
        echo "Branch: ${{ steps.build_info.outputs.git_branch }}" >> build_summary.txt
        echo "Commit: ${{ steps.build_info.outputs.git_sha }}" >> build_summary.txt
        echo "Build Type: ${{ env.CMAKE_BUILD_TYPE }}" >> build_summary.txt
        echo "Build Date: ${{ steps.build_info.outputs.build_date }}" >> build_summary.txt
        echo "Qt Version: ${{ env.QT_VERSION }}" >> build_summary.txt
        echo "Architecture: ${{ env.CMAKE_OSX_ARCHITECTURES }}" >> build_summary.txt
        echo "Code Signed: ${{ inputs.code_sign }}" >> build_summary.txt
        echo "DMG Created: ${{ inputs.create_dmg }}" >> build_summary.txt
        echo "" >> build_summary.txt
        echo "=== App Bundle Info ===" >> build_summary.txt
        echo "Size: $(du -sh ${{ steps.build_info.outputs.app_name }}.app)" >> build_summary.txt
        echo "Binary Architecture:" >> build_summary.txt
        file "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" >> build_summary.txt
        echo "" >> build_summary.txt
        echo "=== Dependencies ===" >> build_summary.txt
        otool -L "${{ steps.build_info.outputs.app_name }}.app/Contents/MacOS/DroidStar" >> build_summary.txt
        
        cat build_summary.txt
    
    - name: Upload app bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build_info.outputs.app_name }}_app
        path: build/${{ steps.build_info.outputs.app_name }}.app
        retention-days: 30
        compression-level: 6
    
    - name: Upload DMG artifact
      if: ${{ inputs.create_dmg }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build_info.outputs.app_name }}_dmg
        path: build/${{ steps.build_info.outputs.app_name }}_${{ steps.build_info.outputs.build_date }}.dmg
        retention-days: 30
    
    - name: Upload build summary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build_info.outputs.app_name }}_build_summary
        path: build/build_summary.txt
        retention-days: 30
    
    - name: Job summary
      run: |
        echo "## 🚀 macOS Build Completed Successfully" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Build Information" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ steps.build_info.outputs.git_branch }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ steps.build_info.outputs.git_sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Type:** ${{ env.CMAKE_BUILD_TYPE }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Architecture:** ARM64 (Apple Silicon)" >> $GITHUB_STEP_SUMMARY
        echo "- **Qt Version:** ${{ env.QT_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Code Signed:** ${{ inputs.code_sign }}" >> $GITHUB_STEP_SUMMARY
        echo "- **DMG Created:** ${{ inputs.create_dmg }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Artifacts Generated" >> $GITHUB_STEP_SUMMARY
        echo "- 📱 **App Bundle:** \`${{ steps.build_info.outputs.app_name }}.app\`" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.create_dmg }}" = "true" ]; then
          echo "- 💿 **DMG Package:** \`${{ steps.build_info.outputs.app_name }}_${{ steps.build_info.outputs.build_date }}.dmg\`" >> $GITHUB_STEP_SUMMARY
        fi
        echo "- 📋 **Build Summary:** \`build_summary.txt\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Usage" >> $GITHUB_STEP_SUMMARY
        echo "Download the artifacts and:" >> $GITHUB_STEP_SUMMARY
        echo "- **App Bundle:** Extract and run directly or copy to Applications" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.create_dmg }}" = "true" ]; then
          echo "- **DMG:** Mount and drag to Applications folder" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All dependencies are bundled - no additional installation required! 🎉" >> $GITHUB_STEP_SUMMARY