on:
 push:
   branches:
     - main
     - develop

jobs:
  build:
    name: mac-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
    - name: install QT6
      run: |
        brew install qt@6
    - name: build
      run: |
        ls -lh
        mkdir build
        cd build
        qmake ./...
        make
    - name: upload
      uses: actions/upload-artifact@v4
      with:
       name: Droidstar-${{ env.sha_short }}-${{ matrix.os }}
       path: build/Droidstar.app
